export type ReviewLspErrorCode =
  | "GIT_COMMAND_FAILED"
  | "CANDIDATE_UNSUPPORTED"
  | "CANDIDATE_PATH_INVALID"
  | "CANDIDATE_INTEGRITY_INVALID"
  | "CANDIDATE_MISMATCH"
  | "CANDIDATE_RESOURCE_LIMIT"
  | "DEPENDENCY_INPUT_INVALID"
  | "DEPENDENCY_UNSUPPORTED"
  | "DEPENDENCY_ACQUISITION_REQUIRED"
  | "DEPENDENCY_ACQUISITION_FAILED"
  | "DEPENDENCY_SNAPSHOT_INVALID"
  | "DEPENDENCY_SNAPSHOT_ESCAPED"
  | "DEPENDENCY_SNAPSHOT_UNSEALED"
  | "PROJECTION_INVALID"
  | "COORDINATE_EXPECTATION_UNMET"
  | "PROFILE_INVALID"
  | "ENVIRONMENT_PARTIAL"
  | "CONTAINER_UNAVAILABLE"
  | "CONTAINER_IMAGE_INVALID"
  | "CONTAINER_ISOLATION_INVALID"
  | "CONTAINER_EXECUTION_FAILED"
  | "LSP_PROTOCOL_ERROR"
  | "LSP_TIMEOUT"
  | "LSP_CANCELLED"
  | "LSP_CAPABILITY_UNSUPPORTED"
  | "RECEIPT_INVALID";

export class ReviewLspError extends Error {
  constructor(public readonly code: ReviewLspErrorCode, message: string) {
    super(`${code}: ${message}`);
    this.name = "ReviewLspError";
  }
}
